### ISSUE TITLE
Add a comment to program "Coding-Practice /Number System Converter.py"

### ISSUE THREAD

**Issue by vamseeachanta** [msd-prasad/Coding-Practice#1]
Add a comment to describe the objective of this program

**Comment by msd-prasad** [comment]
The objective of the program is **to convert numbers from one number system to another**. It allows users to input a number in any base and then specify the base they want to convert that number into. The program achieves this by converting the input number into base 10 first and then converting it to the desired target base. I have **added a comment block at the beginning of the program to make it easier to understand** now.

**Comment by vamseeachanta** [comment]
Looks good.
